name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis: [6.2, 7.4, 8.0]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Get Deno version
        run: |
          echo "DENO_VERSION=$(cat .denov)" >> $GITHUB_ENV
      - name: Set up Deno ${{ env.DENO_VERSION }}
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: ${{ env.DENO_VERSION }}
          cache: true
          cache-hash: ${{ hashFiles('.denov', 'deno.lock') }}
      - name: Set up Redis ${{ matrix.redis }}
        uses: shogo82148/actions-setup-redis@2f3253b148c73d7a0682eae73e862b777a4fa74e # v1.49.0
        with:
          redis-version: ${{ matrix.redis }}
          auto-start: "true"
      - name: Run tests
        run: |
          deno task test
        env:
          REDIS_VERSION: ${{ matrix.redis }}
      - name: Run doc tests
        run: |
          deno task test:doc
      - uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v1.5.0
        if: ${{ github.event_name == 'pull_request' && matrix.redis == 8 }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Get Deno version
        run: |
          echo "DENO_VERSION=$(cat .denov)" >> $GITHUB_ENV
      - name: Set up Deno ${{ env.DENO_VERSION }}
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: ${{ env.DENO_VERSION }}
          cache: true
          cache-hash: ${{ hashFiles('.denov', 'deno.lock') }}
      - name: Run linters
        run: |
          deno task check
      - name: deno publish --dry-run
        run:
          deno publish --dry-run

  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis: [8.0]
        driver: [deno-redis, ioredis]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Get Deno version
        run: |
          echo "DENO_VERSION=$(cat .denov)" >> $GITHUB_ENV
      - name: Set up Deno ${{ env.DENO_VERSION }}
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: ${{ env.DENO_VERSION }}
          cache: true
          cache-hash: ${{ hashFiles('.denov', 'deno.lock') }}
      - name: Set up Node.js
        if: matrix.driver == 'ioredis'
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24"
      - uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # v1.12.1
        if: matrix.driver == 'ioredis'
        with:
          working-directory: benchmark
      - name: Set up Redis ${{ matrix.redis }}
        uses: shogo82148/actions-setup-redis@2f3253b148c73d7a0682eae73e862b777a4fa74e # v1.49.0
        with:
          redis-version: ${{ matrix.redis }}
          auto-start: "true"
      - name: Run benchmarks
        run: |
          deno task bench:${{ matrix.driver }}
      - name: Output results as a job summary
        run: |
          deno run --allow-read=tmp tools/format-benchmark-results.js >> $GITHUB_STEP_SUMMARY
