name: Publish to JSR
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Get Deno version
        run: |
          echo "DENO_VERSION=$(cat .denov)" >> $GITHUB_ENV
      - name: Set up Deno ${{ env.DENO_VERSION }}
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Publish packages
        run:
          deno publish
